feat(visualizations): Improving shareReplay visualization
ajcrites/rxjs-visualize pull request #22
Opened 2019-01-31 01:15 UTC by cpyle0819

* Adding a new output marble
* Removing comment about improvements being needed
* Updating description to include new output names

![sharereplay](https://user-images.githubusercontent.com/2723491/52023608-be3adb00-24cb-11e9-9acb-4ad8e1872e65.gif)

2019-01-31 02:41 UTC, cpyle0819 commented
Closed in favor of #23

2019-01-31 14:29 UTC, ajcrites commented
In order for this to show off the share capabilities it probably needs some sort of console log to indicate that it's only subscribing once (other than the  `<marbles>` subscription).

Otherwise it's all right, but I'd prefer more thoughtful names ... `delayedOutput` or something like that.

2019-01-31 14:31 UTC, cpyle0819 commented
I can rename the variables. Doesn't the fact that the 'replay' happens all at once show off the share capabilities?

2019-01-31 14:31 UTC, ajcrites commented
Another issue that's really just a consequence of the overlapping marbles of the visualization is that it's hard to tell that only `3, 4` are replayed for the delayed output. This should be pointed out if it's not already.

2019-01-31 14:35 UTC, cpyle0819 commented
> Another issue that's really just a consequence of the overlapping marbles of the visualization is that it's hard to tell that only `3, 4` are replayed for the delayed output. This should be pointed out if it's not already.

I was thinking about the over lap. I wonder how it would look to have a hover effect on a marble where it 'expands' vertically all the marbles that are overlapping

2019-01-31 15:41 UTC, ajcrites commented
> Doesn't the fact that the 'replay' happens all at once show off the share capabilities?

This shows off the replay capabilities, not the share capabilities. The point of share is to be able to reuse a source without resubscribing to the original source.

2019-02-02 18:03 UTC, cpyle0819 commented
Did some renaming. Added console logs. Removed the 4th marble I had added as it seemed unnecessary upon reflection.

2019-02-05 13:23 UTC, ajcrites commented on src/app/visualizations/operators/shareReplay.ts
> +      replay any values. <code>shareReplay</code> will replay
The parentheses were intentional here to indicate a call to `shareReplay` with no arguments.

2019-02-05 13:23 UTC, ajcrites requested changes

2019-02-05 13:23 UTC, ajcrites commented on src/app/visualizations/operators/shareReplay.ts
> +  delayedOutput = timer(2000).pipe(mergeMapTo(this.subject));
Is this enough time to limit what is replayed?

2023-10-11 13:24 UTC, closed without merging